const express = require('express');
const router = express.Router();
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const { nanoid } = require('nanoid');
const db = require('../db');
const { getPlanLimits } = require('./auth');

const UPLOADS_DIR = path.join(__dirname, '../../uploads');
if (!fs.existsSync(UPLOADS_DIR)) fs.mkdirSync(UPLOADS_DIR, { recursive: true });

function getApiKey(req) {
  const authHeader = req.headers.authorization || '';
  return authHeader.replace('Bearer ', '').trim() || req.headers['x-api-key'] || req.query.key;
}

function resolveKey(key) {
  if (!key) return null;
  return db.prepare(
    `SELECT k.*, u.username, u.plan
     FROM api_keys k LEFT JOIN users u ON k.user_id = u.id
     WHERE k.key = ? AND k.revoked = 0`
  ).get(key);
}

function parseTTL(ttl) {
  if (!ttl) return 7 * 24 * 3600;
  const match = String(ttl).match(/^(\d+)(s|m|h|d)?$/i);
  if (!match) return 7 * 24 * 3600;
  const n = parseInt(match[1]);
  const unit = (match[2] || 'd').toLowerCase();
  const mult = { s: 1, m: 60, h: 3600, d: 86400 };
  return n * (mult[unit] || 86400);
}

// Multer — stream to temp location, then move after validation
const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, UPLOADS_DIR),
  filename: (req, file, cb) => cb(null, nanoid(24) + path.extname(file.originalname)),
});

const upload = multer({
  storage,
  limits: { fileSize: 100 * 1024 * 1024 * 1024 }, // 100 GB hard ceiling
});

// POST /api/upload — multipart or raw body upload
router.post('/', upload.single('file'), async (req, res) => {
  const rawKey = getApiKey(req);

  // Auto-generate a free key if none provided
  let keyRow;
  let autoGenerated = false;
  if (!rawKey) {
    const { generateKey } = require('./auth');
    const newKey = generateKey();
    db.prepare('INSERT INTO api_keys (key, name, scope) VALUES (?, ?, ?)').run(newKey, 'auto', 'read,write');
    keyRow = db.prepare("SELECT k.*, NULL as username, 'free' as plan FROM api_keys k WHERE k.key = ?").get(newKey);
    autoGenerated = true;
    keyRow._generatedKey = newKey;
  } else {
    keyRow = resolveKey(rawKey);
    if (!keyRow) return res.status(401).json({ error: 'invalid api key' });
  }

  const plan = keyRow.plan || 'free';
  const limits = getPlanLimits(plan);

  // Reset daily counter if needed
  const now = Math.floor(Date.now() / 1000);
  if (now - keyRow.uploads_reset_at > 86400) {
    db.prepare('UPDATE api_keys SET uploads_today = 0, uploads_reset_at = ? WHERE id = ?').run(now, keyRow.id);
    keyRow.uploads_today = 0;
  }

  // Rate limit check
  if (keyRow.uploads_today >= limits.uploads_per_day) {
    if (req.file) fs.unlinkSync(req.file.path);
    return res.status(429).json({
      error: 'daily upload limit reached',
      limit: limits.uploads_per_day,
      plan,
      upgrade_url: 'https://transfa.sh/pricing',
    });
  }

  if (!req.file) {
    return res.status(400).json({ error: 'no file provided — use multipart/form-data with field "file"' });
  }

  // File size check
  if (req.file.size > limits.max_file_size) {
    fs.unlinkSync(req.file.path);
    return res.status(413).json({
      error: 'file too large for your plan',
      max_bytes: limits.max_file_size,
      plan,
    });
  }

  // TTL
  const ttlSeconds = Math.min(
    parseTTL(req.body.ttl || req.headers['x-transfa-ttl'] || '7d'),
    limits.max_ttl_seconds
  );
  const expiresAt = now + ttlSeconds;

  // SHA-256
  const fileBuffer = fs.readFileSync(req.file.path);
  const sha256 = crypto.createHash('sha256').update(fileBuffer).digest('hex');

  // Idempotency: same key + same sha256 → return existing upload
  const existing = db.prepare(
    `SELECT * FROM uploads
     WHERE api_key_id = ? AND sha256 = ? AND deleted_at IS NULL AND expires_at > ?`
  ).get(keyRow.id, sha256, now);

  if (existing) {
    fs.unlinkSync(req.file.path);
    db.prepare('UPDATE api_keys SET last_used_at = ? WHERE id = ?').run(now, keyRow.id);
    const response = {
      id: existing.id,
      url: `${getBaseUrl(req)}/f/${existing.id}`,
      filename: existing.original_filename,
      bytes: existing.size,
      sha256: existing.sha256,
      created_at: new Date(existing.created_at * 1000).toISOString(),
      expires_at: new Date(existing.expires_at * 1000).toISOString(),
      download_count: existing.download_count,
      idempotent: true,
    };
    if (autoGenerated) response.api_key = keyRow._generatedKey;
    return res.json(response);
  }

  const uploadId = nanoid(6);
  const originalFilename = req.body.filename || req.headers['x-transfa-filename'] || req.file.originalname;

  db.prepare(
    `INSERT INTO uploads (id, api_key_id, filename, original_filename, size, sha256, mime_type, storage_path, expires_at, uploader_name, max_downloads)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
  ).run(
    uploadId, keyRow.id, req.file.filename, originalFilename,
    req.file.size, sha256, req.file.mimetype,
    req.file.path, expiresAt,
    keyRow.username || null,
    req.body.max_downloads ? parseInt(req.body.max_downloads) : null
  );

  db.prepare('UPDATE api_keys SET uploads_today = uploads_today + 1, last_used_at = ? WHERE id = ?').run(now, keyRow.id);

  const response = {
    id: uploadId,
    url: `${getBaseUrl(req)}/f/${uploadId}`,
    filename: originalFilename,
    bytes: req.file.size,
    sha256,
    created_at: new Date(now * 1000).toISOString(),
    expires_at: new Date(expiresAt * 1000).toISOString(),
    download_count: 0,
  };
  if (autoGenerated) response.api_key = keyRow._generatedKey;

  res.status(201).json(response);
});

// GET /api/upload — list uploads for authenticated key
router.get('/', (req, res) => {
  const rawKey = getApiKey(req);
  const keyRow = resolveKey(rawKey);
  if (!keyRow) return res.status(401).json({ error: 'invalid api key' });

  const now = Math.floor(Date.now() / 1000);
  const limit = Math.min(parseInt(req.query.limit) || 20, 100);
  const offset = parseInt(req.query.offset) || 0;

  const uploads = db.prepare(
    `SELECT id, original_filename, size, sha256, download_count, expires_at, created_at, uploader_name
     FROM uploads
     WHERE api_key_id = ? AND deleted_at IS NULL
     ORDER BY created_at DESC LIMIT ? OFFSET ?`
  ).all(keyRow.id, limit, offset);

  const total = db.prepare(
    'SELECT COUNT(*) as n FROM uploads WHERE api_key_id = ? AND deleted_at IS NULL'
  ).get(keyRow.id).n;

  res.json({
    uploads: uploads.map(u => ({
      ...u,
      url: `${getBaseUrl(req)}/f/${u.id}`,
      created_at: new Date(u.created_at * 1000).toISOString(),
      expires_at: new Date(u.expires_at * 1000).toISOString(),
      expired: u.expires_at <= now,
    })),
    total,
    limit,
    offset,
  });
});

// DELETE /api/upload/:id
router.delete('/:id', (req, res) => {
  const rawKey = getApiKey(req);
  const keyRow = resolveKey(rawKey);
  if (!keyRow) return res.status(401).json({ error: 'invalid api key' });

  const upload = db.prepare(
    'SELECT * FROM uploads WHERE id = ? AND api_key_id = ? AND deleted_at IS NULL'
  ).get(req.params.id, keyRow.id);

  if (!upload) return res.status(404).json({ error: 'not found' });

  try {
    if (fs.existsSync(upload.storage_path)) fs.unlinkSync(upload.storage_path);
  } catch (e) {}

  db.prepare('UPDATE uploads SET deleted_at = ? WHERE id = ?').run(Math.floor(Date.now() / 1000), upload.id);
  res.json({ deleted: true, id: upload.id });
});

function getBaseUrl(req) {
  return process.env.BASE_URL || `http://${req.headers.host}`;
}

module.exports = router;
